# Generated by Django 6.0.2 on 2026-02-26 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('nationalite', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('isbn', models.CharField(blank=True, max_length=13)),
                ('annee_edition', models.IntegerField(blank=True, null=True)),
                ('maison_edition', models.CharField(blank=True, max_length=200)),
                ('langue', models.CharField(choices=[('fr', 'Français'), ('en', 'Anglais')], default='fr', max_length=5)),
                ('categories', models.CharField(help_text='Sépare les catégories par des virgules, ex: roman,histoire', max_length=200)),
                ('resume', models.TextField(blank=True)),
                ('disponible', models.BooleanField(default=True)),
                ('couverture_avant', models.ImageField(blank=True, null=True, upload_to='couvertures/')),
                ('couverture_arriere', models.ImageField(blank=True, null=True, upload_to='couvertures/')),
                ('premiere_page', models.ImageField(blank=True, null=True, upload_to='pages/')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotheque.auteur')),
            ],
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateField(auto_now_add=True)),
                ('date_retour', models.DateField(blank=True, null=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotheque.etudiant')),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotheque.livre')),
            ],
        ),
    ]
